/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { getDefaultContent } from "./TopNavBar.content";



// Header component with applied rules
function TopNavBar(props) {

  let navigation;
  if (!props.navigation) {
    navigation = getDefaultContent();
  } else {
    navigation = props.navigation;
  }
  console.log(navigation);

  return (
    <header className="flex gap-5 justify-between px-6 py-2 text-center text-white uppercase bg-neutral-700 max-md:flex-wrap max-md:pr-5">
      <nav className="justify-center py-2 pr-4 pl-0.5 text-base leading-6 whitespace-nowrap rounded-md border-2 border-solid border-stone-950">
        Contact Us
      </nav>

      <div className="flex gap-5 justify-between my-auto text-sm leading-5 max-md:flex-wrap max-md:max-w-full">
         {navigation.group[0].level1.map((item, index) => (
              <div tabIndex="0" className="flex-auto text-sm leading-5 whitespace-nowrap cursor-pointer">
              <a href={item.src}>{item.text}</a>
            </div>
        ))} 
      </div>
    </header>
  );
};

export default TopNavBar;